---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
  "ansible.utils": '*'

license_file: LICENSE
name: bgp
description: Ansible Network BGP enables user to manage the BGP resources independent of platforms and perform BGP health checks.
namespace: network
readme: README.md
repository: https://github.com/ansible-collections/network.bgp
issues: https://github.com/ansible-collections/network.bgp/issue

# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
