---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: ../../base/roles/resource_manager
  vars:
    action: 'deploy'
    resources:
      - 'bgp_global'
      - 'bgp_address_family'
