---
- name: Invoke detect function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    action: 'detect'
    resources:
      - 'bgp_global'
      - 'bgp_address_family'
