---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    action: 'persist'
    resources:
      - 'bgp_global'
      - 'bgp_address_family'
    persist_empty: "{{ persist_empty | d(False) }}"
